services:
  - type: web
    name: caderno-de-erros
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan optimize:clear
      php artisan optimize
      chmod -R 775 storage bootstrap/cache
      touch /tmp/database.sqlite
      php artisan migrate --force
    startCommand: php -S 0.0.0.0:8000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite